#!/bin/bash

### Build the genome annotation for H. sapiens
###   using Ensembl and UCSC as sources
### Output: annot/hsa_ensembl.gtf

mkdir -p annot
cd annot

# download gtf from Ensembl
wget ftp://ftp.ensembl.org/pub/release-74/gtf/homo_sapiens/Homo_sapiens.GRCh37.74.gtf.gz
gunzip Homo_sapiens.GRCh37.74.gtf.gz

# for some reason ensembl gtf is missing tRNAs; get it from UCSC
wget ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/tRNAs.txt.gz
gunzip -c tRNAs.txt.gz > hsa_ucsc_trna.txt

# rename chromosomes to UCSC-style
awk 'BEGIN {FS="\t"; OFS="\t"}
     $1 ~ /^[0-9]+|^X|^Y/ { $1 = "chr"$1; print; next }
     $1 == "MT" { $1 = "chrM"; print; next }' Homo_sapiens.GRCh37.74.gtf > \
 hsa_ensembl.gtf

# convert ucsc trnas to GTF and append
awk 'BEGIN {OFS="\t"}
     { print $2,"tRNA","exon",1+$3,$4,".",$7,".",
             "gene_id \""$5"\"; transcript_id \""$5"\";" }' \
  hsa_ucsc_trna.txt >> hsa_ensembl.gtf

# then write annot/curated/hsa_ensembl_class_overlaps.txt by hand
# specifying which classes you'll allow to co-exist in locus clusters
# (i.e., which classes we'll allow lots of cross-mapping between)
